# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/common_public.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63ommon/common_public.proto\x12\x06\x63ommon\"\x19\n\nResultResp\x12\x0b\n\x03msg\x18\x01 \x01(\tB\x0cZ\nrpc/commonb\x06proto3')



_RESULTRESP = DESCRIPTOR.message_types_by_name['ResultResp']
ResultResp = _reflection.GeneratedProtocolMessageType('ResultResp', (_message.Message,), {
  'DESCRIPTOR' : _RESULTRESP,
  '__module__' : 'common.common_public_pb2'
  # @@protoc_insertion_point(class_scope:common.ResultResp)
  })
_sym_db.RegisterMessage(ResultResp)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\nrpc/common'
  _RESULTRESP._serialized_start=38
  _RESULTRESP._serialized_end=63
# @@protoc_insertion_point(module_scope)
