base:
    is_dev : true
    serial_number : 1.0.0
    service_name : example
    service_displayname : exampleserver
    sercice_desc : example微服务
nacos_info:
    ipaddr: "192.155.1.151"
    port: 8848
    namespace: "dev-haibrain"
    group: "dev-haibrain"
    dataid: example
mysql_info:
    host : localhost
    port : 3306
    username : root
    password : 123456
    database : oauth_db
redis_info:
    addrs: ["192.155.1.150:6379"]
    password: Niren1015
    group_name: oauth2
    db: 0
etcd_info:
    addrs: ["192.155.1.150:2379"]
    timeout: 3
consul_addr: http://192.155.1.150:8500
consul_tag: dev
port: 82
